"""L

Revision ID: ccfc9d995eba
Revises: b5d1cce8c36a
Create Date: 2025-12-06 06:51:48.728148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfc9d995eba'
down_revision = 'b5d1cce8c36a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
